apiVersion: v1
kind: Service
metadata:
  name: postgres-exporter
  namespace: monitoring
  labels:
    app: postgres-exporter
spec:
  ports:
    - port: 9187
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: postgres-exporter