apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: postgres-exporter
  namespace: monitoring
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: postgres-exporter
  endpoints:
    - port: http
      interval: 30s
  namespaceSelector:
    matchNames:
      - monitoring